# -- 코드를 입력하세요
# SELECT I.ANIMAL_ID, I.NAME
# FROM ANIMAL_INS I
# LEFT OUTER JOIN ANIMAL_OUTS O 
# ON I.ANIMAL_ID = O.ANIMAL_ID
# WHERE O.ANIMAL_ID IS NULL
# ORDER BY I.ANIMAL_ID

SELECT ANIMAL_OUTS.ANIMAL_ID , ANIMAL_OUTS.NAME
FROM ANIMAL_OUTS
LEFT JOIN ANIMAL_INS
ON ANIMAL_OUTS.ANIMAL_ID = ANIMAL_INS.ANIMAL_ID
WHERE ANIMAL_INS.ANIMAL_ID IS NULL
ORDER BY ANIMAL_OUTS.ANIMAL_ID
