-- 코드를 입력하세요
SELECT B.FLAVOR
FROM JULY A
JOIN FIRST_HALF B
ON A.FLAVOR = B.FLAVOR
GROUP BY FLAVOR
ORDER BY SUM(A.TOTAL_ORDER + B.TOTAL_ORDER) DESC
LIMIT 3

# -- 풀이 2. JOIN 사용
# SELECT F.FLAVOR
#     FROM FIRST_HALF F
#     JOIN JULY J
#         ON F.FLAVOR = J.FLAVOR
#     GROUP BY F.FLAVOR
#     ORDER BY (F.TOTAL_ORDER + SUM(J.TOTAL_ORDER)) DESC
#     LIMIT 3
    
    
# -- 풀이 1. UNION ALL 사용
# SELECT FLAVOR
#     FROM (
#             SELECT FLAVOR, TOTAL_ORDER FROM FIRST_HALF
#             UNION ALL
#             SELECT FLAVOR, TOTAL_ORDER FROM JULY
#          ) BASE
#     GROUP BY FLAVOR
#     ORDER BY SUM(TOTAL_ORDER) DESC
#     LIMIT 3
