-- 코드를 입력하세요
SELECT B.BOOK_ID, A.AUTHOR_NAME, DATE_FORMAT(B.PUBLISHED_DATE,'%Y-%m-%d') AS PUBLISHED_DATE #대문자로하면 년도는 4자리, 소문자로 하면 2자리 / 나머지는 대문자하면 풀네임, 소문자하면 숫자
FROM BOOK B
INNER JOIN AUTHOR A
ON B.AUTHOR_ID = A.AUTHOR_ID
WHERE B.CATEGORY LIKE '경제'
ORDER BY B.PUBLISHED_DATE

# SELECT BOOK_ID, AUTHOR_NAME, 
#        DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
# FROM BOOK JOIN AUTHOR USING(AUTHOR_ID)
# WHERE CATEGORY = '경제'
# ORDER BY PUBLISHED_DATE 


# SELECT 
#     BO.BOOK_ID, 
#     AU.AUTHOR_NAME, 
#     DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
# FROM AUTHOR AU 
# INNER JOIN BOOK BO
# ON AU.AUTHOR_ID = BO.AUTHOR_ID
# WHERE BO.CATEGORY LIKE '경제'
# ORDER BY BO.PUBLISHED_DATE ASC;